name: Haskell CI

on:
  push:
    branches: [ "master" ]
    paths: 
      - src/*
      - test/*
      - .github/workflows/*
  pull_request:
    branches: [ "master" ]
    paths:
      - src/*
      - test/*

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache GHC and Cabal
      id: cache-ghc
      uses: actions/cache@v3
      with:
        path: |
          /home/runner/.cabal
          /home/runner/.ghcup
          /opt/hostedtoolcache/ghcup
        key: ${{ runner.os }}-ghc-8.10.3-cabal-3.2-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-ghc-8.10.3-cabal-3.2-
          ${{ runner.os }}-ghc-8.10.3-
    
    - uses: actions/checkout@v4
    
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
        enable-stack: false

    - name: Test solution only on main
      if: github.ref == 'refs/heads/master'
      run: |
        bash prepare-main-for-tests.sh
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run test week 03
      run: cabal test week03
    - name: Run test week 04
      run: cabal test week04
    - name: Run test week 05
      run: cabal test week05
    - name: Run test week 06
      run: cabal test week06
