name: Haskell CI

on:
  push:
    branches: [ "master" ]
    paths: 
      - src/*
      - test/*
  pull_request:
    branches: [ "master" ]
    paths:
      - src/*
      - test/*

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache GHC and Cabal
      uses: actions/cache@v3
      env:
        cache-name: cache-ghc-cabal
      with:
        path: |
          ~/.cabal
          ~/.ghcup
          ~/.local/bin
        key: ${{ runner.os }}-build-${{ env.cache-name }}-ghc-8.10.3-cabal-3.2-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-ghc-8.10.3-cabal-3.2-
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    - name: Test solution only on main
      if: github.ref == 'refs/heads/master'
      run: |
        bash prepare-main-for-tests.sh
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run test week 03
      run: cabal test week03
    - name: Run test week 04
      run: cabal test week04
